# Generated by Django 4.0.5 on 2022-06-08 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datosdircine', '0003_alter_genero_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pelicula',
            old_name='director',
            new_name='direct',
        ),
    ]
