# Generated by Django 4.0.5 on 2022-06-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datosdircine', '0002_director_pelicula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='name',
            field=models.CharField(help_text='pon el nombre del genero', max_length=64),
        ),
    ]
