# Generated by Django 4.0.5 on 2022-06-08 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datosdircine', '0005_director_named_alter_genero_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='nacionalidad',
            field=models.CharField(default='', help_text='Pais de origen', max_length=40),
            preserve_default=False,
        ),
    ]
